# streamlit_app.py
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

st.title("Cluster Resource Usage Dashboard")

@st.cache_data
def load_data():
    df = pd.read_csv("processed_logs.csv")
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
    df = df.dropna(subset=["timestamp"]).sort_values("timestamp")
    return df

df = load_data()

st.write("### Summary Statistics")
st.write(df.describe())

# --- CPU Utilization Over Time ---
st.write("### CPU Utilization Over Time")
fig_cpu, ax_cpu = plt.subplots()
ax_cpu.plot(df["timestamp"], df["cpu_percent"], color="tab:blue", linewidth=1.5)
ax_cpu.set_xlabel("Time")
ax_cpu.set_ylabel("CPU Usage (%)")
ax_cpu.set_title("CPU Utilization Over Time")
st.pyplot(fig_cpu)

# --- Node Utilization Over Time ---
st.write("### Node Utilization Over Time")
fig_nodes, ax_nodes = plt.subplots()
ax_nodes.plot(df["timestamp"], df["node_utilization"], color="tab:green", linewidth=1.5)
ax_nodes.set_xlabel("Time")
ax_nodes.set_ylabel("Node Utilization (%)")
ax_nodes.set_title("Node Utilization Over Time")
st.pyplot(fig_nodes)

# --- Job Queue Trends ---
st.write("### Job Queue Dynamics")
fig_jobs, ax_jobs = plt.subplots()
ax_jobs.plot(df["timestamp"], df["jobs_running"], label="Running", linewidth=1)
ax_jobs.plot(df["timestamp"], df["jobs_queued"], label="Queued", linewidth=1)
ax_jobs.plot(df["timestamp"], df["jobs_held"], label="Held", linewidth=1)
ax_jobs.plot(df["timestamp"], df["jobs_exiting"], label="Exiting", linewidth=1)
ax_jobs.set_xlabel("Time")
ax_jobs.set_ylabel("Number of Jobs")
ax_jobs.set_title("Jobs Over Time")
ax_jobs.legend()
st.pyplot(fig_jobs)

# --- Node State Trends ---
st.write("### Node States Over Time")
fig_states, ax_states = plt.subplots()
ax_states.plot(df["timestamp"], df["nodes_running"], label="Running", linewidth=1.2)
ax_states.plot(df["timestamp"], df["nodes_offline"], label="Offline", linewidth=1.2)
ax_states.plot(df["timestamp"], df["nodes_total"], label="Total", linewidth=1.2)
ax_states.set_xlabel("Time")
ax_states.set_ylabel("Number of Nodes")
ax_states.set_title("Node States Over Time")
ax_states.legend()
st.pyplot(fig_states)

# --- Latest Snapshot ---
st.write("### Latest Snapshot")
st.write(df.tail(1))

st.caption("Data source: processed_logs.csv (generated by processed_logs.py)")

